# Generated by Django 4.1.5 on 2023-01-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex_no', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
                ('form', models.CharField(blank=True, max_length=20, null=True)),
                ('type1', models.CharField(blank=True, max_length=10, null=True)),
                ('type2', models.CharField(blank=True, max_length=10, null=True)),
                ('ability1', models.CharField(blank=True, max_length=20, null=True)),
                ('ability2', models.CharField(blank=True, max_length=20, null=True)),
                ('ability_d', models.CharField(blank=True, max_length=20, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('defence', models.IntegerField(blank=True, null=True)),
                ('sp_attack', models.IntegerField(blank=True, null=True)),
                ('sp_defence', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pokemons',
                'managed': False,
            },
        ),
    ]
