# Generated by Django 4.1.5 on 2023-01-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonsv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('pp', models.IntegerField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('acuury', models.IntegerField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('direct', models.IntegerField(blank=True, null=True)),
                ('number_times_max', models.IntegerField(blank=True, null=True)),
                ('number_times_min', models.IntegerField(blank=True, null=True)),
                ('on_hit', models.IntegerField(blank=True, null=True)),
                ('machine_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'moves',
                'managed': False,
            },
        ),
    ]
